export const GET_INGREDIENTS_STARTED = 'GET_INGREDIENTS_STARTED';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILURE = 'GET_INGREDIENTS_FAILURE';
export const SET_INGREDIENT_PAGE = 'SET_INGREDIENT_PAGE';

