spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: rcb
    password:
    data: classpath:data-dev.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  resources:
    static-locations:
      - classpath:/static/
      - file:c:/users/root/ideaProjects/resources
server:
  port: ${PORT:8080}